### ISSUE TITLE
Packaging IPredict

### ISSUE THREAD

**Issue by VeenitShah** [tedgueniche/IPredict#3]
Hi,

How do I package IPredict in a jar file? I have a python application where I would like to invoke this jar file and get the output back in Python?

Any thoughts?

Regards,
V

**Comment by rafkt** [comment]
Are you using jPype library? Because you don't necessarily need to create a jar file. You can just start the JVM from your python script, create an object of MainController (for example) using jPype methods and then invoke a method from the object that you created.

**Comment by VeenitShah** [comment]
I can use the JPype library. It's new. (0.6.1) I'm looking at their documentation and some example code. Are there any other alternatives?

**Comment by tedgueniche** [comment]
Hi, 
what are you trying to accomplish and what kind of interaction do you need? You will most likely need to implement a new [controller](https://github.com/tedgueniche/IPredict/tree/master/src/ca/ipredict/controllers). Concerning the .jar, I am able to generate it from Eclipse directly:

-Ensure you imported the project into Eclipse and that you are able to execute your controller
-Right click on your project in the "Package Explorer" and select "Export"
-Select "Runnable JAR file" under "Java"
-Select your Launch configuration, such as "MainController - IPredict"
-Select an export destination and ensure you selected "Extract required libraries into generated JAR"
-Click "finish"

**Comment by VeenitShah** [comment]
Okay, so I was playing around with the JPype library but apparently it doesn't seem to work. 

I have the below code - 

```
from jpype import *
startJVM("/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/jli/libjli.dylib", 
         "-ea -Djava.class.path=/Users/e22654/workspace/ipython/Jpype")
 
java.lang.System.out.println("Hello to Java from Python")
MakePrediction = JPackage("src").ca.ipredict.controllers.MakePrediction
mp = MakePrediction()
op = mp.predict(JString("20 4 32 12 8 24"))
print op, type(op)
```

I get the following error output = 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-61cc6830869f> in <module>()
----> 1 mp = MakePrediction()
      2 op = mp.predict(JString("20 4 32 12 8 24"))
      3 print op, type(op)

//anaconda/lib/python2.7/site-packages/JPype1-0.6.1-py2.7-macosx-10.6-x86_64.egg/jpype/_jpackage.pyc in __call__(self, *arg, **kwarg)
     53 
     54     def __call__(self, *arg, **kwarg):
---> 55         raise TypeError("Package {0} is not Callable".format(self.__name))

TypeError: Package src.ca.ipredict.controllers.MakePrediction is not Callable
```

The above code and the `src` folder is placed in the same folder. Is there anything that I am missing?

**Comment by tedgueniche** [comment]
What is your src.ca.ipredict.controllers.MakePrediction class? Are you using the one from the repository (I updated it today) or did you write it yourself? If you wrote it yourself, could you show me its content?

**Comment by VeenitShah** [comment]
Yes. It's the same class that you checked in. Just that, I put all of the contents of the main method in a `predict()` so that I can call it in python.

**Comment by VeenitShah** [comment]
I figured it out. It was the `src` folder that needed to be removed. I can now successfully invoke this functionality from python. Please find the below code for reference - 

```
from jpype import *
startJVM("/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/jli/libjli.dylib", 
         "-ea -Djava.class.path=...path to ca folder...")
MakePrediction = JPackage("ca").ipredict.controllers.MakePrediction
mp = MakePrediction()
op = mp.predict(JString("20 4 32 12 8 24"))
print op, type(op)
```

Closing this. Thank you for your help.
