### ISSUE TITLE
Sequence ID for prediction?

### ISSUE THREAD

**Issue by VeenitShah** [tedgueniche/IPredict#4]
What's the importance of Sequence ID while I am trying to predict the next item in sequence? 

For e.g. Let's say I have trained my model with 5 sequences already. Each sequence was given a sequence id starting from 1 to 5. Now, if my prediction sequence is `4 1 3 2`, what should be my input sequence id for this string? 

I'm getting the same prediction for different inputs all of a sudden. I want to understand if there is anything obvious that I am missing while training/testing

**Comment by philfv** [comment]
Hello,
A sequence ID is just an identifier that is used to distinguish between different sequences. You can consider that it is the "name" of the sequence.  Sequence identifiers should be unique.  So if your five training sequences have the IDs  1 to 5, then  the next sequence should have the ID 6 or anything else that is different from 1 to 5.   
So each training sequences should have a different ID.  Now for prediction, I am not sure as I did not check the code for a while but I guess that the fact that IDs should be unique may apply to sequences that are used for prediction. So if you want to be safe, you may assign a different ID than 1 to 5. 
Best,
Philippe
    On Friday, July 8, 2016 11:44 PM, Veenit Shah <notifications@github.com> wrote:
 

 What's the importance of Sequence ID while I am trying to predict the next item in sequence? For e.g. Let's say I have trained my model with 5 sequences already. Each sequence was given a sequence id starting from 1 to 5. Now, if my prediction sequence is 4 1 3 2, what should be my input sequence id for this string? I'm getting the same prediction for different inputs all of a sudden. I want to understand if there is anything obvious that I am missing while training/testing—

**Comment by VeenitShah** [comment]
Thank you, Philippe. That helps. I would love to contribute documentation to this library. Is there any predefined template for documentation which I can start contributing with?

Closing this. :)
