### ISSUE TITLE
Ability to save a trained model as a .model file?

### ISSUE THREAD

**Issue by VeenitShah** [tedgueniche/IPredict#5]
Hi,

I would like to know if it's possible to save a trained model as a `.model` file (or any such extension). I have really long sequences in my training set and every time I want to make a prediction, I do not want to retrain it just to make a single prediction.

If I can save the trained model, I would just have to read the trained model and make a prediction which would be really quick. 

Are there any other alternatives to this approach? Looking forward to your inputs.

**Comment by philfv** [comment]
Hi, 
How about serializing the Java object into a file using serialization and then unserialize the object to read it from the file?  It can be done with the standard java api if the model implement the interface Serializable (I did not check) or you could do it using  some library such as XStream. 

Sent from Yahoo Mail on Android 
 
  On Tue, Jul 12, 2016 at 1:09, Veenit Shah<notifications@github.com> wrote:   
Hi,

I would like to know if it's possible to save a trained model as a .model file (or any such extension). I have really long sequences in my training set and every time I want to make a prediction, I do not want to retrain it just to make a single prediction.

If I can save the trained model, I would just have to read the trained model and make a prediction which would be really quick. 

Are there any other alternatives to this approach? Looking forward to your inputs.

**Comment by VeenitShah** [comment]
I'm using a python wrapper `jpype` to invoke this module. I cannot serialize it in java and deserialize it in python. Are there any other ideas/alternatives?

**Comment by tedgueniche** [comment]
Hi, 
Like PhilFV suggested, java serialization should work in your case. Have a look in the [SerializeController.java](https://github.com/tedgueniche/IPredict/blob/master/src/ca/ipredict/controllers/SerializePredictor.java). You should be able to train a predictor and save it to a file. Then in jpype, you should be able to call a method like SerializePredictor.load(...) to load your model back.

**Comment by VeenitShah** [comment]
Thank you so much for the sample code. Closing this issue.
